from __future__ import annotations

import hashlib
import re
import unicodedata
from datetime import UTC, datetime
from typing import Any

from .canonical import content_hash
from .models import (
    ActorReference,
    ActorType,
    Anchor,
    AnchorResolutionStatus,
    AnchorType,
    Claim,
    ClaimType,
    Concern,
    ConcernOrigin,
    ConcernOriginType,
    ConcernStatus,
    Explicitness,
    Severity,
    VerificationGrade,
)

CONFIDENCE_MAP = {"low": 0.35, "medium": 0.65, "high": 0.90}
SEVERITY_MAP = {
    "critical": Severity.CRITICAL,
    "major": Severity.MAJOR,
    "minor": Severity.MINOR,
}


def _stable_id(prefix: str, *parts: str) -> str:
    digest = hashlib.sha256("\x1f".join(parts).encode("utf-8")).hexdigest()[:20]
    return f"{prefix}_{digest}"


def normalize_quote(text: str) -> str:
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"-\s*\n\s*", "", text)
    return re.sub(r"\s+", " ", text).strip()


def resolve_quote(quote: str, extracted_text: str | None) -> AnchorResolutionStatus:
    if extracted_text is None:
        return AnchorResolutionStatus.UNRESOLVED
    exact_count = extracted_text.count(quote)
    if exact_count == 1:
        return AnchorResolutionStatus.EXACT
    if exact_count > 1:
        return AnchorResolutionStatus.AMBIGUOUS
    normalized_quote = normalize_quote(quote)
    normalized_text = normalize_quote(extracted_text)
    normalized_count = normalized_text.count(normalized_quote)
    if normalized_count == 1:
        return AnchorResolutionStatus.NORMALIZED
    if normalized_count > 1:
        return AnchorResolutionStatus.AMBIGUOUS
    return AnchorResolutionStatus.UNRESOLVED


def convert_coarse_review(
    review: dict[str, Any],
    *,
    manuscript_version_id: str,
    run_id: str,
    extracted_text: str | None = None,
) -> tuple[list[Anchor], list[Claim], list[Concern]]:
    actor = ActorReference(actor_id="coarse", actor_type=ActorType.SYSTEM, display_name="Coarse")
    now = datetime.now(UTC)
    anchors: list[Anchor] = []
    claims: list[Claim] = []
    concerns: list[Concern] = []

    for index, comment in enumerate(review.get("detailed_comments", []), start=1):
        title = str(comment.get("title", f"Coarse comment {index}"))
        quote = str(comment.get("quote", "")).strip()
        feedback = str(comment.get("feedback", "")).strip()
        severity_raw = str(comment.get("severity", "major")).lower()
        confidence_raw = str(comment.get("confidence", "medium")).lower()
        severity = SEVERITY_MAP.get(severity_raw, Severity.MAJOR)
        confidence = CONFIDENCE_MAP.get(confidence_raw, 0.65)

        anchor_id = _stable_id("oca", manuscript_version_id, str(index), quote)
        anchor_payload = {
            "id": anchor_id,
            "schema_version": "0.1.0",
            "created_at": now,
            "created_by": actor,
            "content_hash": "0" * 64,
            "anchor_id": anchor_id,
            "manuscript_version_id": manuscript_version_id,
            "anchor_type": AnchorType.TEXT_SPAN,
            "page_start": None,
            "page_end": None,
            "bounding_boxes": [],
            "section_path": [],
            "source_text": quote,
            "normalized_text": normalize_quote(quote),
            "object_label": None,
            "object_coordinates": {},
            "extraction_confidence": None,
            "rendered_reference": None,
            "resolution_status": resolve_quote(quote, extracted_text),
        }
        anchor_payload["content_hash"] = content_hash(anchor_payload)
        anchor = Anchor.model_validate(anchor_payload)
        anchors.append(anchor)

        claim_id = _stable_id("ocl", manuscript_version_id, str(index), title)
        claim_payload = {
            "id": claim_id,
            "schema_version": "0.1.0",
            "created_at": now,
            "created_by": actor,
            "content_hash": "0" * 64,
            "claim_id": claim_id,
            "manuscript_version_id": manuscript_version_id,
            "statement": f"Candidate claim reconstructed from Coarse comment: {title}",
            "claim_type": ClaimType.INTERPRETIVE,
            "explicitness": Explicitness.INFERRED,
            "scope": "Unresolved until expert claim reconstruction",
            "anchor_ids": [anchor_id],
            "dependency_claim_ids": [],
            "reconstruction_notes": (
                "Automatically generated by the Coarse adapter; requires expert review."
            ),
            "approval_status": "candidate",
        }
        claim_payload["content_hash"] = content_hash(claim_payload)
        claim = Claim.model_validate(claim_payload)
        claims.append(claim)

        concern_id = _stable_id("occ", manuscript_version_id, str(index), title, feedback)
        concern_payload = {
            "id": concern_id,
            "schema_version": "0.1.0",
            "created_at": now,
            "created_by": actor,
            "content_hash": "0" * 64,
            "concern_id": concern_id,
            "manuscript_version_id": manuscript_version_id,
            "title": title,
            "summary": feedback,
            "concern_type": "adapter.coarse.unclassified",
            "claim_ids": [claim_id],
            "anchor_ids": [anchor_id],
            "severity": severity,
            "confidence": confidence,
            "verification_grade": VerificationGrade.V0,
            "status": ConcernStatus.PROPOSED,
            "potential_consequence": (
                feedback if severity in {Severity.CRITICAL, Severity.MAJOR} else ""
            ),
            "required_resolution": None,
            "resolution_disposition": None,
            "uncertainty_sources": [],
            "origin": ConcernOrigin(
                origin_type=ConcernOriginType.REVIEWER_SYSTEM,
                origin_id="coarse",
                run_id=run_id,
                original_severity=severity_raw,
                original_confidence=confidence_raw,
            ),
        }
        concern_payload["content_hash"] = content_hash(concern_payload)
        concerns.append(Concern.model_validate(concern_payload))

    return anchors, claims, concerns
