"""initial_registry_schema

Revision ID: e47498e63a9d
Revises: 
Create Date: 2026-07-28 14:31:15.730610

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47498e63a9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_target', ['target_type', 'target_id'], unique=False)

    op.create_table('benchmark_versions',
    sa.Column('registry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benchmark_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('case_set_hash', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('predecessor_version', sa.String(length=64), nullable=True),
    sa.Column('created_from_determination_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('registry_id'),
    sa.UniqueConstraint('benchmark_id', 'version', name='uq_benchmark_version')
    )
    op.create_table('concern_index',
    sa.Column('concern_id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('submitted_severity', sa.String(length=32), nullable=False),
    sa.Column('submitted_confidence', sa.Float(), nullable=False),
    sa.Column('concern_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('concern_id')
    )
    with op.batch_alter_table('concern_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concern_index_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concern_index_concern_type'), ['concern_type'], unique=False)

    op.create_table('determinations',
    sa.Column('determination_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('concern_id', sa.String(length=255), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('requires_tie_break', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('submission_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('determination_id')
    )
    with op.batch_alter_table('determinations', schema=None) as batch_op:
        batch_op.create_index('ix_determination_concern', ['concern_id', 'created_at'], unique=False)

    op.create_table('novel_candidates',
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=255), nullable=False),
    sa.Column('submission_id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('candidate_json', sa.JSON(), nullable=False),
    sa.Column('candidate_hash', sa.String(length=64), nullable=False),
    sa.Column('source_result_hash', sa.String(length=64), nullable=False),
    sa.Column('source_submission_hash', sa.String(length=64), nullable=False),
    sa.Column('matcher_version', sa.String(length=128), nullable=False),
    sa.Column('matcher_config_id', sa.String(length=128), nullable=False),
    sa.Column('benchmark_id', sa.String(length=255), nullable=False),
    sa.Column('benchmark_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    with op.batch_alter_table('novel_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_novel_candidate_case', ['case_id', 'case_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_novel_candidates_result_id'), ['result_id'], unique=False)

    op.create_table('principals',
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principals_role'), ['role'], unique=False)

    op.create_table('scorecard_records',
    sa.Column('scorecard_id', sa.String(length=64), nullable=False),
    sa.Column('scorecard_hash', sa.String(length=64), nullable=False),
    sa.Column('scorecard_json', sa.JSON(), nullable=False),
    sa.Column('result_id', sa.String(length=255), nullable=False),
    sa.Column('benchmark_id', sa.String(length=255), nullable=False),
    sa.Column('benchmark_version', sa.String(length=64), nullable=False),
    sa.Column('reference_set_hash', sa.String(length=64), nullable=False),
    sa.Column('scoring_policy_version', sa.String(length=64), nullable=False),
    sa.Column('predecessor_scorecard_id', sa.String(length=64), nullable=True),
    sa.Column('predecessor_scorecard_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('scorecard_id'),
    sa.UniqueConstraint('scorecard_hash')
    )
    with op.batch_alter_table('scorecard_records', schema=None) as batch_op:
        batch_op.create_index('ix_scorecard_predecessor', ['predecessor_scorecard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scorecard_records_result_id'), ['result_id'], unique=False)

    op.create_table('adjudication_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('concern_id', sa.String(length=255), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('case_id', 'case_version', 'concern_id', 'slot', name='uq_task_slot')
    )
    with op.batch_alter_table('adjudication_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjudication_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjudication_tasks_concern_id'), ['concern_id'], unique=False)
        batch_op.create_index('ix_task_claim', ['status', 'slot', 'created_at'], unique=False)

    op.create_table('api_tokens',
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_actor_id'), ['actor_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('rights_classification', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('sha256')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_rights_classification'), ['rights_classification'], unique=False)

    op.create_table('calibration_sets',
    sa.Column('set_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_profile', sa.String(length=128), nullable=False),
    sa.Column('case_refs', sa.JSON(), nullable=False),
    sa.Column('min_cases', sa.Integer(), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('max_false_critical', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    with op.batch_alter_table('calibration_sets', schema=None) as batch_op:
        batch_op.create_index('ix_calibration_set_domain', ['domain_profile', 'active'], unique=False)

    op.create_table('cases',
    sa.Column('registry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('case_type', sa.String(length=40), nullable=False),
    sa.Column('rights_classification', sa.String(length=32), nullable=False),
    sa.Column('bundle_hash', sa.String(length=64), nullable=False),
    sa.Column('bundle_json', sa.JSON(), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('registry_id'),
    sa.UniqueConstraint('case_id', 'case_version', name='uq_case_version')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('ix_cases_rights', ['rights_classification'], unique=False)

    op.create_table('claim_reconstruction_determinations',
    sa.Column('determination_id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('canonical_claim_json', sa.JSON(), nullable=True),
    sa.Column('submission_ids', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('determination_id')
    )
    with op.batch_alter_table('claim_reconstruction_determinations', schema=None) as batch_op:
        batch_op.create_index('ix_claim_determination_intake', ['intake_id', 'created_at'], unique=False)

    op.create_table('compensation_records',
    sa.Column('compensation_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('compensation_id'),
    sa.UniqueConstraint('task_type', 'task_id', name='uq_compensation_task')
    )
    with op.batch_alter_table('compensation_records', schema=None) as batch_op:
        batch_op.create_index('ix_compensation_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensation_records_actor_id'), ['actor_id'], unique=False)

    op.create_table('contribution_credits',
    sa.Column('credit_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('contribution_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('public_name', sa.String(length=255), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('credit_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('credit_id'),
    sa.UniqueConstraint('actor_id', 'contribution_type', 'target_id', name='uq_credit_target')
    )
    with op.batch_alter_table('contribution_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_credits_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_credit_actor', ['actor_id', 'created_at'], unique=False)

    op.create_table('expert_profiles',
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('methodologies', sa.JSON(), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('orcid', sa.String(length=32), nullable=True),
    sa.Column('public_attribution', sa.Boolean(), nullable=False),
    sa.Column('attribution_name', sa.String(length=255), nullable=True),
    sa.Column('compensation_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('novel_adjudication_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['novel_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('candidate_id', 'slot', name='uq_novel_task_slot')
    )
    with op.batch_alter_table('novel_adjudication_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novel_adjudication_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_novel_adjudication_tasks_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index('ix_novel_task_claim', ['status', 'slot', 'created_at'], unique=False)

    op.create_table('novel_determinations',
    sa.Column('determination_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('determination_json', sa.JSON(), nullable=False),
    sa.Column('determination_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('requires_tie_break', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['novel_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('determination_id')
    )
    with op.batch_alter_table('novel_determinations', schema=None) as batch_op:
        batch_op.create_index('ix_novel_determination_candidate', ['candidate_id', 'created_at'], unique=False)

    op.create_table('use_grants',
    sa.Column('grant_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('use_type', sa.String(length=64), nullable=False),
    sa.Column('basis', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    with op.batch_alter_table('use_grants', schema=None) as batch_op:
        batch_op.create_index('ix_grant_lookup', ['case_id', 'case_version', 'use_type', 'status'], unique=False)

    op.create_table('adjudication_submissions',
    sa.Column('adjudication_id', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('concern_id', sa.String(length=255), nullable=False),
    sa.Column('adjudicator_id', sa.String(length=255), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['adjudication_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('adjudication_id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('adjudication_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjudication_submissions_adjudicator_id'), ['adjudicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjudication_submissions_concern_id'), ['concern_id'], unique=False)

    op.create_table('artifact_case_links',
    sa.Column('link_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['sha256'], ['artifacts.sha256'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('case_id', 'case_version', 'sha256', name='uq_case_artifact')
    )
    with op.batch_alter_table('artifact_case_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_case_links_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_case_links_sha256'), ['sha256'], unique=False)

    op.create_table('calibration_attempts',
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('set_id', sa.String(length=64), nullable=False),
    sa.Column('adjudicator_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score_json', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['calibration_sets.set_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('calibration_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_calibration_attempt_actor', ['adjudicator_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_attempts_adjudicator_id'), ['adjudicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_attempts_set_id'), ['set_id'], unique=False)

    op.create_table('case_intakes',
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_artifact_sha256', sa.String(length=64), nullable=False),
    sa.Column('domain_profile', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('rights_classification', sa.String(length=32), nullable=False),
    sa.Column('requested_uses', sa.JSON(), nullable=False),
    sa.Column('rights_attestation', sa.JSON(), nullable=False),
    sa.Column('contains_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('contains_personal_data', sa.Boolean(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['source_artifact_sha256'], ['artifacts.sha256'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['principals.actor_id'], ),
    sa.PrimaryKeyConstraint('intake_id')
    )
    with op.batch_alter_table('case_intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_intakes_submitted_by'), ['submitted_by'], unique=False)
        batch_op.create_index('ix_intake_status', ['status', 'created_at'], unique=False)

    op.create_table('novel_adjudication_submissions',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('adjudicator_id', sa.String(length=255), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['novel_adjudication_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('novel_adjudication_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novel_adjudication_submissions_adjudicator_id'), ['adjudicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_novel_adjudication_submissions_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('calibration_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('concern_id', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['calibration_attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('attempt_id', 'concern_id', name='uq_calibration_attempt_concern')
    )
    with op.batch_alter_table('calibration_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_calibration_task_attempt', ['attempt_id', 'status'], unique=False)

    op.create_table('claim_reconstruction_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('anchor_context', sa.JSON(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['case_intakes.intake_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('intake_id', 'slot', name='uq_claim_reconstruction_slot')
    )
    with op.batch_alter_table('claim_reconstruction_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_reconstruction_tasks_intake_id'), ['intake_id'], unique=False)
        batch_op.create_index('ix_claim_task_claim', ['status', 'slot', 'created_at'], unique=False)

    op.create_table('expert_qualifications',
    sa.Column('qualification_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('domain_profile', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_attempt_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['calibration_attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    with op.batch_alter_table('expert_qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expert_qualifications_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_qualification_lookup', ['actor_id', 'domain_profile', 'status'], unique=False)

    op.create_table('calibration_submissions',
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('adjudicator_id', sa.String(length=255), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['calibration_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('claim_reconstruction_submissions',
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('adjudicator_id', sa.String(length=255), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('claim_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['principals.actor_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['claim_reconstruction_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('claim_reconstruction_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_reconstruction_submissions_intake_id'), ['intake_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim_reconstruction_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_reconstruction_submissions_intake_id'))

    op.drop_table('claim_reconstruction_submissions')
    op.drop_table('calibration_submissions')
    with op.batch_alter_table('expert_qualifications', schema=None) as batch_op:
        batch_op.drop_index('ix_qualification_lookup')
        batch_op.drop_index(batch_op.f('ix_expert_qualifications_actor_id'))

    op.drop_table('expert_qualifications')
    with op.batch_alter_table('claim_reconstruction_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_task_claim')
        batch_op.drop_index(batch_op.f('ix_claim_reconstruction_tasks_intake_id'))

    op.drop_table('claim_reconstruction_tasks')
    with op.batch_alter_table('calibration_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_calibration_task_attempt')

    op.drop_table('calibration_tasks')
    with op.batch_alter_table('novel_adjudication_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novel_adjudication_submissions_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_novel_adjudication_submissions_adjudicator_id'))

    op.drop_table('novel_adjudication_submissions')
    with op.batch_alter_table('case_intakes', schema=None) as batch_op:
        batch_op.drop_index('ix_intake_status')
        batch_op.drop_index(batch_op.f('ix_case_intakes_submitted_by'))

    op.drop_table('case_intakes')
    with op.batch_alter_table('calibration_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_attempts_set_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_attempts_adjudicator_id'))
        batch_op.drop_index('ix_calibration_attempt_actor')

    op.drop_table('calibration_attempts')
    with op.batch_alter_table('artifact_case_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_case_links_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifact_case_links_case_id'))

    op.drop_table('artifact_case_links')
    with op.batch_alter_table('adjudication_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjudication_submissions_concern_id'))
        batch_op.drop_index(batch_op.f('ix_adjudication_submissions_adjudicator_id'))

    op.drop_table('adjudication_submissions')
    with op.batch_alter_table('use_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_grant_lookup')

    op.drop_table('use_grants')
    with op.batch_alter_table('novel_determinations', schema=None) as batch_op:
        batch_op.drop_index('ix_novel_determination_candidate')

    op.drop_table('novel_determinations')
    with op.batch_alter_table('novel_adjudication_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_novel_task_claim')
        batch_op.drop_index(batch_op.f('ix_novel_adjudication_tasks_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_novel_adjudication_tasks_assigned_to'))

    op.drop_table('novel_adjudication_tasks')
    op.drop_table('expert_profiles')
    with op.batch_alter_table('contribution_credits', schema=None) as batch_op:
        batch_op.drop_index('ix_credit_actor')
        batch_op.drop_index(batch_op.f('ix_contribution_credits_actor_id'))

    op.drop_table('contribution_credits')
    with op.batch_alter_table('compensation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compensation_records_actor_id'))
        batch_op.drop_index('ix_compensation_actor')

    op.drop_table('compensation_records')
    with op.batch_alter_table('claim_reconstruction_determinations', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_determination_intake')

    op.drop_table('claim_reconstruction_determinations')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_rights')

    op.drop_table('cases')
    with op.batch_alter_table('calibration_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_calibration_set_domain')

    op.drop_table('calibration_sets')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_rights_classification'))

    op.drop_table('artifacts')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_actor_id'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('adjudication_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_task_claim')
        batch_op.drop_index(batch_op.f('ix_adjudication_tasks_concern_id'))
        batch_op.drop_index(batch_op.f('ix_adjudication_tasks_assigned_to'))

    op.drop_table('adjudication_tasks')
    with op.batch_alter_table('scorecard_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scorecard_records_result_id'))
        batch_op.drop_index('ix_scorecard_predecessor')

    op.drop_table('scorecard_records')
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principals_role'))

    op.drop_table('principals')
    with op.batch_alter_table('novel_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novel_candidates_result_id'))
        batch_op.drop_index('ix_novel_candidate_case')

    op.drop_table('novel_candidates')
    with op.batch_alter_table('determinations', schema=None) as batch_op:
        batch_op.drop_index('ix_determination_concern')

    op.drop_table('determinations')
    with op.batch_alter_table('concern_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concern_index_concern_type'))
        batch_op.drop_index(batch_op.f('ix_concern_index_case_id'))

    op.drop_table('concern_index')
    op.drop_table('benchmark_versions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_target')
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
